name: The Hive
favicon: null
layout_spectrum: 0.21147753344848752
typography_spectrum: 0.3669660484883934
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.49379598326049745
  lightness: 0.12100427062250674
  saturation: 0.2108392813242972
  rhythmicContrast: 0.5429204015526921
purpose: []
